# Generated by Django 5.1.4 on 2025-01-13 09:01

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
