# Generated by Django 5.1.4 on 2025-01-13 10:43

import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_doc_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='Image link here'),
        ),
        migrations.AlterField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
