# Generated by Django 5.1.4 on 2025-01-13 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_image_alter_document_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
