# Generated by Django 5.1.4 on 2025-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.CharField(blank=True, default='Image link here', max_length=500),
        ),
    ]
