# Generated by Django 5.1.4 on 2025-01-14 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
