# Generated by Django 5.1.4 on 2025-01-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_doc_code_alter_doc_content_alter_doc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=100)),
            ],
        ),
    ]
